/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IBxs:badge': typeof import('~icons/bxs/badge')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IMaterialSymbols:login': typeof import('~icons/material-symbols/login')['default']
    IMaterialSymbolsLogin: typeof import('~icons/material-symbols/login')['default']
    'IPixelarticons:cornerDownRight': typeof import('~icons/pixelarticons/corner-down-right')['default']
    'IPixelarticons:moon': typeof import('~icons/pixelarticons/moon')['default']
    'IPixelarticons:sunAlt': typeof import('~icons/pixelarticons/sun-alt')['default']
    'IPixelarticons:user': typeof import('~icons/pixelarticons/user')['default']
    IPixelarticonsCornerDownRight: typeof import('~icons/pixelarticons/corner-down-right')['default']
    IPixelarticonsKeyboard: typeof import('~icons/pixelarticons/keyboard')['default']
    IPixelarticonsLock: typeof import('~icons/pixelarticons/lock')['default']
    IPixelarticonsMail: typeof import('~icons/pixelarticons/mail')['default']
    IPixelarticonsMoon: typeof import('~icons/pixelarticons/moon')['default']
    IPixelarticonsSunAlt: typeof import('~icons/pixelarticons/sun-alt')['default']
    IPixelarticonsUser: typeof import('~icons/pixelarticons/user')['default']
    IPixelUser: typeof import('~icons/pixel/user')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    PixelButton: typeof import('./src/components/common/PixelButton.vue')['default']
    PixelCard: typeof import('./src/components/common/PixelCard.vue')['default']
    PixelInput: typeof import('./src/components/common/PixelInput.vue')['default']
    RegisterForm: typeof import('./src/components/register/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
