/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChannelList: typeof import('./src/components/chatroom/ChannelList.vue')['default']
    ChatroomLayout: typeof import('./src/components/common/ChatroomLayout.vue')['default']
    ChatRoomLayout: typeof import('./src/components/common/ChatRoomLayout.vue')['default']
    Dialog: typeof import('./src/components/common/Dialog.vue')['default']
    DirectMessageChatArea: typeof import('./src/components/chatroom/DirectMessageChatArea.vue')['default']
    DIrectMessageChatArea: typeof import('./src/components/chatroom/DIrectMessageChatArea.vue')['default']
    DirectMessageList: typeof import('./src/components/chatroom/DirectMessageList.vue')['default']
    FormItem: typeof import('./src/components/common/FormItem.vue')['default']
    'IBxs:badge': typeof import('~icons/bxs/badge')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IEosIcons:bubbleLoading': typeof import('~icons/eos-icons/bubble-loading')['default']
    'IHugeicons:callEnd04': typeof import('~icons/hugeicons/call-end04')['default']
    'IIconamoon:microphoneLight': typeof import('~icons/iconamoon/microphone-light')['default']
    'IMaterialSymbols:androidCameraOutline': typeof import('~icons/material-symbols/android-camera-outline')['default']
    'IMaterialSymbols:login': typeof import('~icons/material-symbols/login')['default']
    'IMaterialSymbols:personAddOutline': typeof import('~icons/material-symbols/person-add-outline')['default']
    IMaterialSymbolsLogin: typeof import('~icons/material-symbols/login')['default']
    'IPixelarticons:close': typeof import('~icons/pixelarticons/close')['default']
    'IPixelarticons:cornerDownRight': typeof import('~icons/pixelarticons/corner-down-right')['default']
    'IPixelarticons:logout': typeof import('~icons/pixelarticons/logout')['default']
    'IPixelarticons:moon': typeof import('~icons/pixelarticons/moon')['default']
    'IPixelarticons:sunAlt': typeof import('~icons/pixelarticons/sun-alt')['default']
    'IPixelarticons:user': typeof import('~icons/pixelarticons/user')['default']
    'IPixelarticons:video': typeof import('~icons/pixelarticons/video')['default']
    'IPixelarticons:warningBox': typeof import('~icons/pixelarticons/warning-box')['default']
    IPixelarticonsCornerDownRight: typeof import('~icons/pixelarticons/corner-down-right')['default']
    IPixelarticonsKeyboard: typeof import('~icons/pixelarticons/keyboard')['default']
    IPixelarticonsLock: typeof import('~icons/pixelarticons/lock')['default']
    IPixelarticonsLogout: typeof import('~icons/pixelarticons/logout')['default']
    IPixelarticonsMail: typeof import('~icons/pixelarticons/mail')['default']
    IPixelarticonsMessage: typeof import('~icons/pixelarticons/message')['default']
    IPixelarticonsMoon: typeof import('~icons/pixelarticons/moon')['default']
    IPixelarticonsSunAlt: typeof import('~icons/pixelarticons/sun-alt')['default']
    IPixelarticonsUser: typeof import('~icons/pixelarticons/user')['default']
    IPixelPlaneSolid: typeof import('~icons/pixel/plane-solid')['default']
    IPixelUser: typeof import('~icons/pixel/user')['default']
    'IStreamlinePixel:interfaceEssentialSettingCog': typeof import('~icons/streamline-pixel/interface-essential-setting-cog')['default']
    'ISvgSpinners:12DotsScaleRotate': typeof import('~icons/svg-spinners/12-dots-scale-rotate')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    MessageItem: typeof import('./src/components/chatroom/MessageItem.vue')['default']
    PixelButton: typeof import('./src/components/common/PixelButton.vue')['default']
    PixelCard: typeof import('./src/components/common/PixelCard.vue')['default']
    PixelInput: typeof import('./src/components/common/PixelInput.vue')['default']
    RegisterForm: typeof import('./src/components/register/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowButton: typeof import('./src/components/common/ShadowButton.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    UserInfoPannel: typeof import('./src/components/common/UserInfoPannel.vue')['default']
  }
}
